version: 0.2
phases:
  install:
    commands:
      - echo "Fixing PowerShell permissions"
      - chmod 755 /opt/microsoft/powershell/7.5.0/pwsh
      - ls -la /opt/microsoft/powershell/7.5.0/pwsh  # Verify new permissions
      - echo "Testing PowerShell execution"
      - echo "Diagnostic Information:"
      - uname -a
      - whoami
      - groups
  pre_build:
    commands:
      - pwsh --version
